---
- name: Prepare all Elastic hosts
  hosts: elastic
  roles:
    - common

- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elasticsearch

- name: Install Kibana
  hosts: kibana
  roles:
    - kibana

- name: Install Logstash
  hosts: logstash
  roles:
    - logstash
